workflows:
  react-native-ios:
    name: Build and publish React Native iOS app to TestFlight
    environment:
      node: 16
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.yourcompany.yourapp"  # ← From ios/YourApp/Info.plist
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
          cd ..
      - name: Build IPA
        script: |
          xcodebuild -workspace ios/YourApp.xcworkspace \
                     -scheme YourApp \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath build/YourApp.xcarchive \
                     archive

          xcodebuild -exportArchive \
                     -archivePath build/YourApp.xcarchive \
                     -exportOptionsPlist ios/ExportOptions.plist \
                     -exportPath build/ios
    artifacts:
      - build/ios/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
